<?php
$service_problems = (
    $this->statusSummary->services_warning_handled_on_ok_hosts ||
    $this->statusSummary->services_warning_unhandled_on_ok_hosts ||
    $this->statusSummary->services_critical_handled_on_ok_hosts ||
    $this->statusSummary->services_critical_unhandled_on_ok_hosts ||
    $this->statusSummary->services_unknown_handled_on_ok_hosts ||
    $this->statusSummary->services_unknown_unhandled_on_ok_hosts
);
?>
<div class="box state_<?= $this->statusSummary->hosts_up ? 'up' : 'pending'; ?> col-1-2">
	<div class="details clearfix">
		<div class="graph-donut square">
			<?= $this->img('img/segments.svg') ?>
			<div class="meta">
				<div class="wrap">
					<span class="count-big critical">12</span>
					<span class="count-label">Services down</span>
					<span class="count-label critical-handled">2 handled</span>
				</div>
			</div>
		</div>
		<div class="panel">
			<table>
				<tbody>
					<tr class="ok"><th>OK</th><td>20</td><td></td></tr>
					<tr class="warning"><th>Warning</th><td>12</td><td>20</td></tr>
					<tr class="critical"><th>Critical</th><td>2</td><td>1</td></tr>
					<tr class="pending"><th>Pending</th><td>2</td><td></td></tr>
				</tbody>
				<tfoot>
					<tr><th>Total</th><td>100</td><td></td></tr>
				</tfoot>
			</table>
		</div>
	</div>
</div>
