<div class="box problem_hosts col-1-2">
	<div class="details clearfix">
		<div class="graph-donut square">
			<?= $this->img('img/segments.svg') ?>
			<div class="meta">
				<div class="wrap">
					<span class="count-big critical">12</span>
					<span class="count-label">Hosts down</span>
				</div>
			</div>
		</div>
		<div class="panel">
			<table>
				<tbody>
					<tr class="ok"><th>OK</th><td>20</td></tr>
					<tr class="warning"><th>Warning</th><td>12</td></tr>
					<tr class="critical"><th>Critical</th><td>2</td></tr>
					<tr class="pending"><th>Pending</th><td>2</td></tr>
				</tbody>
				<tfoot>
					<tr><th>Total</th><td>100</td></tr>
				</tfoot>
			</table>
		</div>
	</div>
</div>
