<?php
use Icinga\Module\Monitoring\Object\Host;

if (! $this->compact): ?>
<div class="controls">
    <?= $this->tabs; ?>
    <?= $this->sortBox; ?>
    <?= $this->limiter; ?>
    <?= $this->paginator; ?>
    <?= $this->filterEditor; ?>
</div>
<?php endif ?>
<div class="content" data-base-target="_next">
    <div class="group-grid">
<?php
if (count($hostgroups) === 0) {
    echo $this->translate('No hostgroups found matching the filter') . '</div>';
    return;
}
foreach ($hostgroups as $h) {
    if ($h->hosts_down_unhandled) {
        $handled = false;
        $state = Host::STATE_DOWN;
    } elseif ($h->hosts_unreachable_unhandled) {
        $handled = false;
        $state = Host::STATE_UNREACHABLE;
    } else {
        $handled = true;
        if ($h->hosts_down_handled) {
            $state = Host::STATE_DOWN;
        } elseif ($h->hosts_unreachable_handled) {
            $state = Host::STATE_UNREACHABLE;
        } elseif ($h->hosts_up) {
            $state = Host::STATE_UP;
        } else {
            $state = Host::STATE_PENDING;
        }
    }
?>
        <div class="group-grid item">
            <div class="state-indicator <?= Host::getStateText($state) . ($handled ? ' handled' : '') ?>"
                 title="<?= sprintf($this->translate('State %s'), Host::getStateText($state, true)) ?>"></div>
            <?= $this->qlink(
            $h->hostgroup_alias,
            'monitoring/list/servicegrid',
            array('hostgroup_name' => $h->hostgroup_name),
            array('title' => sprintf($this->translate('Show the grid for hosts in the group "%s"'), $h->hostgroup_alias))
            ) ?>
        </div>
    <?php } ?>
    </div>
</div>
