<?php if (! $this->compact): ?>
<div class="controls">
    <?= $this->tabs ?>
    <?= $this->paginator ?>
</div>
<?php endif ?>
<div class="content">
    <table class="table-row-selectable common-table" data-base-target="_next">
    <thead>
    <tr>
        <th><?= $this->translate('Module') ?></th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($modules as $module): ?>
        <tr>
            <td>
                <?php if ($module->enabled) {
                    if ($module->dangling) {
                        echo $this->icon('trash', sprintf($this->translate('Module %s is dangling'), $module->name));
                    } elseif ($module->loaded) {
                        echo $this->icon('thumbs-up', sprintf($this->translate('Module %s is enabled'), $module->name));
                    } else {
                        echo $this->icon('block', sprintf($this->translate('Module %s has failed to load'), $module->name));
                    }
                } else {
                    echo $this->icon('block', sprintf($this->translate('Module %s is disabled'), $module->name));
                }

                echo $this->qlink(
                    $module->name,
                    'config/module/',
                    array('name' => $module->name),
                    array(
                        'class' => 'rowaction',
                        'title' => sprintf($this->translate('Show the overview of the %s module'), $module->name)
                    )
                ); ?>
            </td>
        </tr>
    <?php endforeach ?>
    </tbody>
    </table>
</div>
